--- Las tablas tienen prefijo S_ para facilitar su acceso desde SQL Developer
create sequence SUPERANDES_SEQUENCE;


-- Creación de la tabla S_SUPERMERCADO con sus restricciones
CREATE TABLE S_SUPERMERCADO
(NIT NUMBER NOT NULL,
 NOMBRE VARCHAR2(255 BYTE) NOT NULL,

 CONSTRAINT S_SUPERMERCADO_NIT_PK PRIMARY KEY (NIT)
);


-- Creación de la tabla S_SUCURSAL con sus restricciones
CREATE TABLE S_SUCURSAL
(NITSUPERMERCADO NUMBER,
 ID NUMBER,
 NOMBRE VARCHAR2(255 BYTE) NOT NULL,
 TAMANIO REAL NOT NULL,
 CIUDAD VARCHAR2(255 BYTE) NOT NULL,

 CONSTRAINT FK_NITSUPERMERCADO
     FOREIGN KEY (NITSUPERMERCADO)
         REFERENCES S_SUPERMERCADO(NIT),
 CONSTRAINT PK_IDSUCURSAL PRIMARY KEY (ID),
 CONSTRAINT CK_TAMANIO CHECK (TAMANIO > 40 ),
 CONSTRAINT UN_NOMBRESUCUR UNIQUE (NOMBRE)

);


-- Creación de la tabla S_CATEGORIA con sus restricciones
CREATE TABLE S_CATEGORIA
(ID NUMBER,
 NOMBRE VARCHAR2(255 BYTE) NOT NULL,

 CONSTRAINT PK_IDCATEGORIA PRIMARY KEY (ID),
 CONSTRAINT CK_NOMBRE CHECK (NOMBRE IN('Bebidas','Charcuteria','Granos','Lacteos',
                                       'Embutidos','HigienePersonal','Aseo-Limpieza','Electrodomesticos','pescaderia',
                                       'Frutas-Verduras','Enlatados','Abarrotes','Otros'))
);




-- Creación de la tabla S_ALMACENAMIENTO con sus restricciones
CREATE TABLE S_ALMACENAMIENTO
(IDSUCURSAL NUMBER NOT NULL,
 ID NUMBER NOT NULL,
 IDCATEGORIA NUMBER NOT NULL,
 TIPO VARCHAR2(50 BYTE) NOT NULL,
 VOLUMEN REAL NOT NULL,
 PESO REAL NOT NULL,
 AREAOCUPADA REAL NOT NULL,
 PESOOCUPADO REAL NOT NULL,

 CONSTRAINT FK_IDSUCURSAL
     FOREIGN KEY(IDSUCURSAL)
         REFERENCES S_SUCURSAL(ID),
 CONSTRAINT FK_IDALMACENAMIENTO PRIMARY KEY (ID),
 CONSTRAINT FK_IDCATEGORIA
     FOREIGN KEY (IDCATEGORIA)
         REFERENCES S_CATEGORIA(ID),
 CONSTRAINT CK_TIPO CHECK(TIPO IN ('bodega','estanteria'))
);



-- Creación de la tabla S_PRESENTACION con sus restricciones
CREATE TABLE S_PRESENTACION
(ID NUMBER NOT NULL,
 PRECIOPORUNIDAD REAL NOT NULL,
 UNIDADDEMEDIDA VARCHAR2(10 BYTE) NOT NULL,
 ESPECIFICACION VARCHAR2(50 BYTE) NOT NULL,


 CONSTRAINT PK_IDPRESENTACION PRIMARY KEY (ID),
 CONSTRAINT CK_UNIDADDEMEDIDA CHECK(UNIDADDEMEDIDA IN ('gr','kg','lt','ml'))
);






-- Creación de la tabla S_PROVEEDOR con sus restricciones
CREATE TABLE S_PROVEEDOR
(IDSUCURSAL NUMBER NOT NULL,
 ID NUMBER NOT NULL,
 NIT NUMBER NOT NULL,
 NOMBRE VARCHAR2 (100 BYTE) NOT NULL,
 TELEFONO NUMBER NOT NULL,
 DIRECCION VARCHAR2(100 BYTE) NOT NULL,

 CONSTRAINT FK_IDSUCURSAL_PROVEEDOR
     FOREIGN KEY (IDSUCURSAL)
         REFERENCES S_SUCURSAL(ID),
 CONSTRAINT PK_IDPROVEEDOR PRIMARY KEY(ID),
 CONSTRAINT UN_NIT UNIQUE (NIT)
);

CREATE TABLE S_ORDENCONSOLIDADA
(ID NUMBER NOT NULL,
 IDSUCURSAL NUMBER NOT NULL,
 idPROVEEDOR NUMBER NOT NULL,
 CONSTRAINT PK_IDORDENCONSOLIDADA PRIMARY KEY (ID),
 CONSTRAINT FK_IDSUCURSALORDENCONSOLIDADA
     FOREIGN KEY(IDSUCURSAL)
         REFERENCES S_SUCURSAL(ID),
 CONSTRAINT  FK_NITPROVEEDORORDENCONSOLIDADA
     FOREIGN KEY(IDPROVEEDOR)
         REFERENCES S_PROVEEDOR(ID)
);




-- Creación de la tabla S_PRODUCTO con sus restricciones
CREATE TABLE S_PRODUCTO
(IDPRESENTACION NUMBER NOT NULL,
 IDCATEGORIA NUMBER NOT NULL,
 IDPROVEEDOR NUMBER NOT NULL,
 CODIGODEBARRAS VARCHAR2(255 BYTE),
 NOMBRE VARCHAR2(255 BYTE) NOT NULL,
 MARCA  VARCHAR2(255 BYTE) NOT NULL,


 CONSTRAINT FK_IDPRESENTACION
     FOREIGN KEY (IDPRESENTACION)
         REFERENCES S_PRESENTACION(ID),
 CONSTRAINT FK_IDPROVEEDOR_PRODUCTO
     FOREIGN KEY (IDPROVEEDOR)
         REFERENCES S_PROVEEDOR(ID),
 CONSTRAINT PK_CODIGODEBARRAS PRIMARY KEY (CODIGODEBARRAS),
 CONSTRAINT FK_IDCATEGORIAIA
     FOREIGN KEY (IDCATEGORIA)
         REFERENCES S_CATEGORIA(ID)
);
-- Creación de la tabla S_ORDENPEDIDO con sus restricciones
CREATE TABLE S_ORDENPEDIDO
(IDSUCURSAL NUMBER NOT NULL,
 IDPROVEEDOR NUMBER NOT NULL,
 ID NUMBER,
 FECHA DATE NOT NULL,
 FECHAENTREGAESPERADA DATE NOT NULL,
 PRECIOTOTAL NUMBER NOT NULL,
 IDORDENCONSOLIDADA NUMBER,
 CODIGODEBARRAS VARCHAR2(255 BYTE) NOT NULL,
 CANTIDAD NUMBER NOT NULL,

 CONSTRAINT FK_IDSUCURSAL_ORDENPEDIDO
     FOREIGN KEY (IDSUCURSAL)
         REFERENCES S_SUCURSAL(ID),
 CONSTRAINT FK_IDPROVEDOR_ORDENPEDIDO
     FOREIGN KEY (IDPROVEEDOR)
         REFERENCES S_PROVEEDOR (ID),
 CONSTRAINT PK_IDORDENPEDIDO PRIMARY KEY (ID),
 CONSTRAINT FK_IDORDENCONSOLIDADA
     FOREIGN KEY (IDORDENCONSOLIDADA)
         REFERENCES S_ORDENCONSOLIDADA (ID),
 CONSTRAINT FK_PRODUCTO_ORDENPEDIDO
     FOREIGN KEY (CODIGODEBARRAS)
         REFERENCES S_PRODUCTO (CODIGODEBARRAS)
);
-- Creación de la tabla S_LOTE con sus restricciones
CREATE TABLE S_LOTE
(IDALMACENAMIENTO NUMBER NOT NULL,
 ID NUMBER,
 CODIGODEBARRAS VARCHAR2(250 BYTE) NOT NULL,
 UNIDADES NUMBER NOT NULL,
 FECHAVENCIMIENTO DATE NOT NULL,
 PESO NUMBER ,
 AREA NUMBER ,

 CONSTRAINT FK_IDALMACENAMIENTO_LOTE
     FOREIGN KEY (IDALMACENAMIENTO)
         REFERENCES S_ALMACENAMIENTO (ID),
 CONSTRAINT PK_IDLOTE PRIMARY KEY (ID),
 CONSTRAINT FK_LOTE_PRODUCTO
     FOREIGN KEY (CODIGODEBARRAS)
         REFERENCES S_PRODUCTO (CODIGODEBARRAS)
);

-- Creación de la tabla S_TIPOOFERTA con sus restricciones
CREATE TABLE S_TIPOOFERTA
(ID NUMBER,
 NOMBRE VARCHAR2(255 BYTE) NOT NULL,
 CONSTRAINT PK_IDTIPOOFERTA PRIMARY KEY (ID));


-- Creación de la tabla S_OFERTA con sus restricciones
CREATE TABLE S_OFERTA
(CODIGODEBARRAS VARCHAR2(255 BYTE) NOT NULL,
 ID NUMBER,
 UNIDADESDISPONIBLES NUMBER NOT NULL,
 ACTIVA VARCHAR2(3 BYTE) NOT NULL,
 FECHACADUCIDAD DATE NOT NULL,
 IDTIPOOFERTA NUMBER NOT NULL,
 CONSTRAINT FK_CODIGODEBARRAS
     FOREIGN KEY (CODIGODEBARRAS)
         REFERENCES S_PRODUCTO(CODIGODEBARRAS),
 CONSTRAINT PK_IDOFERTA PRIMARY KEY(ID),
 CONSTRAINT CK_ACTIVA CHECK (ACTIVA IN ('Y','N')),
 CONSTRAINT FK_TIPOOFERTA
     FOREIGN KEY (IDTIPOOFERTA)
         REFERENCES S_TIPOOFERTA(ID)
);

-- Creación de la tabla S_OFERTADESCUENTO con sus restricciones
CREATE TABLE S_OFERTADESCUENTO
(ID NUMBER,
 DESCUENTO NUMBER,
 CONSTRAINT PK_DESCUENTO PRIMARY KEY(ID),
 CONSTRAINT FK_OFERTE
     FOREIGN KEY (ID)
         REFERENCES S_OFERTA(ID)
);

CREATE TABLE S_OFERTA_NXM
(ID NUMBER,
 N NUMBER,
 M NUMBER,
 CONSTRAINT PK_NXM PRIMARY KEY(ID),
 CONSTRAINT FK_OFERTA_NXM
     FOREIGN KEY (ID)
         REFERENCES S_OFERTA(ID)
);

CREATE TABLE S_OFERTA_PAGUEXLLEVEY
(ID NUMBER,
 x NUMBER,
 y NUMBER,
 CONSTRAINT PK_xy PRIMARY KEY(ID),
 CONSTRAINT FK_S_OFERTA_PAGUEXLLEVEY
     FOREIGN KEY (ID)
         REFERENCES S_OFERTA(ID)
);

-- Creación de la tabla S_CLIENTE con sus restricciones
CREATE TABLE S_CLIENTE
(NUMDOC NUMBER NOT NULL,
 TIPODOC VARCHAR2(10 BYTE) NOT NULL,
 NOMBRE VARCHAR2 (70 BYTE) NOT NULL,
 CORREO VARCHAR2 (70 BYTE) NOT NULL,
 MEDIOPAGO VARCHAR2 (30 BYTE) NOT NULL,
 PUNTOS NUMBER NOT NULL,

 CONSTRAINT PK_NUMDOC PRIMARY KEY (NUMDOC),
 CONSTRAINT CK_TIPODOC
     CHECK (TIPODOC IN ('C.C','NIT','T.I','C.E')),
 CONSTRAINT CK_MEDIOPAGO
     CHECK (MEDIOPAGO IN ('Tarjeta','Efectivo','Nequi'))
);


-- Creación de la tabla S_FACTURA con sus restricciones
CREATE TABLE S_FACTURA
(TIPODOC VARCHAR2(10 BYTE) ,
 NUMDOC NUMBER ,
 ID NUMBER ,
 FECHA DATE NOT NULL,
 PRECIO NUMBER NOT NULL,
 IDSUCURSAL NUMBER NOT NULL,

 CONSTRAINT FK_NUMDOC
     FOREIGN KEY (NUMDOC)
         REFERENCES S_CLIENTE(NUMDOC),
 CONSTRAINT PK_IDFACTURA PRIMARY KEY (ID),
 CONSTRAINT FK_IDSUCURSAL_FACTURA
     FOREIGN KEY (IDSUCURSAL)
         REFERENCES S_SUCURSAL(ID)
);


-- Creación de la tabla S_PRODUCTOVENDIDO con sus restricciones
CREATE TABLE S_PRODUCTOVENDIDO
(IDFACTURA NUMBER NOT NULL,
 CODIGODEBARRAS VARCHAR2(255 BYTE) NOT NULL,
 ID NUMBER NOT NULL,
 CANTIDAD NUMBER NOT NULL,

 CONSTRAINT FK_IDFACTURA_PRODUCTOVENDIDO
     FOREIGN KEY (IDFACTURA)
         REFERENCES S_FACTURA(ID),
 CONSTRAINT FK_CODIGODEBARRAS_PRODUCTOVENDIDO
     FOREIGN KEY (CODIGODEBARRAS)
         REFERENCES S_PRODUCTO(CODIGODEBARRAS),
 CONSTRAINT PK_IDPRODUCTOVENDIDO PRIMARY KEY (ID)
);




-- Creación de la tabla S_ROL con sus restricciones
CREATE TABLE S_ROL
(ID NUMBER NOT NULL,
 NOMBRE VARCHAR2(40 BYTE) NOT NULL,

 CONSTRAINT PK_IDROL PRIMARY KEY (ID),
 CONSTRAINT CK_NOMBRE_ROL CHECK (NOMBRE IN ('Administrador','Gerente General',
                                            'Gerente Sucursal','Operador','Cajero')),
 CONSTRAINT UN_NOMBRE UNIQUE(NOMBRE)
);


-- Creación de la tabla S_USUARIO con sus restricciones
CREATE TABLE S_USUARIO
(IDROL NUMBER NOT NULL,
 CEDULA NUMBER NOT NULL,
 IDSUCURSAL NUMBER NOT NULL,
 NITSUPERMERCADO NUMBER NOT NULL,
 NOMBRE VARCHAR2(100 BYTE) NOT NULL,
 CORREO VARCHAR2(100 BYTE) NOT NULL,
 PALABRACLAVE VARCHAR2(50 BYTE) NOT NULL,


 CONSTRAINT PK_CEDULA PRIMARY KEY (CEDULA),
 CONSTRAINT FK_IDSUCURSAL_USUARIO
     FOREIGN KEY (IDSUCURSAL)
         REFERENCES S_SUCURSAL(ID),
 CONSTRAINT FK_NITSUPERMERCADO_USUARIO
     FOREIGN KEY (NITSUPERMERCADO)
         REFERENCES S_SUPERMERCADO(NIT),
 CONSTRAINT FK_ROLID_USUARIO
     FOREIGN KEY (IDROL)
         REFERENCES S_ROL(ID)
);


-- Creación de la tabla S_ORDENENTREGADA con sus restricciones
CREATE TABLE S_ORDENENTREGADA
(IDORDENENTREGADA NUMBER NOT NULL,
 FECHA DATE NOT NULL,
 CODIGODEBARRAS VARCHAR2(255 BYTE) NOT NULL,
CANTIDAD NUMBER NOT NULL,

 CONSTRAINT PK_ORDENENTREGADA PRIMARY KEY (IDORDENENTREGADA),
 CONSTRAINT FK_PRODUCTO_ORDENENTREGADA
     FOREIGN KEY (CODIGODEBARRAS)
         REFERENCES S_PRODUCTO(CODIGODEBARRAS)) ;


-- Creación de la tabla S_CARRITO con sus restricciones
CREATE TABLE S_CARRITO
(IDCARRITO NUMBER NOT NULL,
 ASIGNADO VARCHAR(1 BYTE) NOT NULL,
 CLIENTENUMDOC NUMBER ,

 CONSTRAINT PK_IDCARRITO PRIMARY KEY (IDCARRITO),
 CONSTRAINT FK_CARRITO_CLIENTE
     FOREIGN KEY (CLIENTENUMDOC)
         REFERENCES S_CLIENTE (NUMDOC),
 CONSTRAINT UN_CLIENTECARRITO UNIQUE(CLIENTENUMDOC)
);


-- Creación de la tabla S_PRODUCTOABANDONADO con sus restricciones
CREATE TABLE S_PRODUCTOABANDONADO
(IDPRODUCTOABANDONADO NUMBER NOT NULL,
 CANTIDAD NUMBER NOT NULL,

 CONSTRAINT PK_IDPRODUCTOABANDONADO PRIMARY KEY (IDPRODUCTOABANDONADO)
);


-- Creación de la tabla S_CARRITOSABANDONADOS con sus restricciones
CREATE TABLE S_CARRITOSABANDONADOS
(NUMDOCCLIENTE NUMBER NOT NULL,
 IDPRODUCTABANDONADO NUMBER NOT NULL,

 CONSTRAINT FK_NUMDOCC_CLIENTE
     FOREIGN KEY (NUMDOCCLIENTE)
         REFERENCES S_CLIENTE(NUMDOC),
 CONSTRAINT FK_IDPRODUCTOABANDONADO
     FOREIGN KEY (IDPRODUCTABANDONADO)
         REFERENCES S_PRODUCTOABANDONADO(IDPRODUCTOABANDONADO)
);


CREATE TABLE S_CARRITO_PRODUCTO
(IDCARRITO NUMBER NOT NULL,
 CODIGODEBARRAS VARCHAR2 (255 BYTE) NOT NULL,
 CANTIDAD NUMBER NOT NULL,

 CONSTRAINT FK_IDCARRITO_CARRITO_PRODUCTO
     FOREIGN KEY (IDCARRITO)
         REFERENCES S_CARRITO(IDCARRITO),
 CONSTRAINT FK_CODIGODEBARRAS_CARRITO_PRODUCTO
     FOREIGN KEY (CODIGODEBARRAS)
         REFERENCES S_PRODUCTO(CODIGODEBARRAS)
);

commit;