
-- USO
-- Copie el contenido deseado de este archivo en una pesta�a SQL de SQL Developer
-- Ejec�telo como un script - Utilice el bot�n correspondiente de la pesta�a utilizada
    
-- Eliminar todas las tablas de la base de datos

DROP TABLE S_LOTE CASCADE CONSTRAINTS;
DROP TABLE S_OFERTA CASCADE CONSTRAINTS;
DROP TABLE S_ORDENENTREGADA CASCADE CONSTRAINTS;
DROP TABLE S_PRODUCTOVENDIDO CASCADE CONSTRAINTS;
DROP TABLE S_PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE S_USUARIO CASCADE CONSTRAINTS;
DROP TABLE S_ALMACENAMIENTO CASCADE CONSTRAINTS;
DROP TABLE S_FACTURA CASCADE CONSTRAINTS;
DROP TABLE S_ORDENPEDIDO CASCADE CONSTRAINTS;
DROP TABLE S_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE S_SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE S_SUPERMERCADO CASCADE CONSTRAINTS;
DROP TABLE S_CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE S_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE S_PRESENTACION CASCADE CONSTRAINTS;
DROP TABLE S_ROL CASCADE CONSTRAINTS;
DROP TABLE S_TIPOOFERTA CASCADE CONSTRAINTS;
DROP TABLE S_OFERTADESCUENTO CASCADE CONSTRAINTS;
DROP TABLE S_OFERTA_NXM CASCADE CONSTRAINTS;
DROP TABLE S_OFERTA_PAGUEXLLEVEY CASCADE CONSTRAINTS;
DROP TABLE S_CARRITO CASCADE CONSTRAINTS;
DROP TABLE S_CARRITO_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE S_CARRITOSABANDONADOS CASCADE CONSTRAINTS;
DROP TABLE S_PRODUCTOABANDONADO CASCADE CONSTRAINTS;
DROP TABLE S_ORDENCONSOLIDADA CASCADE CONSTRAINTS;
commit;

-- Eliminar el contenido de todas las tablas de la base de datos
DELETE FROM S_LOTE;
DELETE FROM S_OFERTA;
DELETE FROM S_ORDENENTREGADA;
DELETE FROM S_PRODUCTOPROVEEDOR;
DELETE FROM S_PRODUCTOVENDIDO;
DELETE FROM S_PROVEEDOR;
DELETE FROM S_USUARIO;
DELETE FROM S_ALMACENAMIENTO;
DELETE FROM S_FACTURA;
DELETE FROM S_ORDENPEDIDO;
DELETE FROM S_PRODUCTO;
DELETE FROM S_SUCURSAL;
DELETE FROM S_SUPERMERCADO;
DELETE FROM S_CATEGORIA;
DELETE FROM S_CLIENTE;
DELETE FROM S_PRESENTACION;
DELETE FROM S_ROL;
commit;